// Opt-in web-font stylesheets: `import '@mono-lit/helper/ui/font/<name>.css'`.
//
// Each sheet is generated by UnoCSS — `presetWebFonts` with the LOCAL processor —
// so the font is downloaded at build time and self-hosted: the sheet's @font-face
// rules point at `./files/<name>-<hash>.woff2` beside it, and an app makes no
// request to Google at runtime.
//
// Kept OUT of dist/ui/index.css on purpose: an app picks which faces it ships (the
// ONE flavor's Poppins, or none — a Basecoat style brings its own font), and an
// asset referenced from a package's CSS is served from node_modules, which an app's
// `server.fs.allow` must then permit (Vite 403s it otherwise).
//
// IMPORTING A SHEET MAKES THAT FONT UNIVERSAL. Besides its @font-face rules every sheet
// sets one override hook on :root — `--mono-font-sans` (a sans sheet) or `--mono-font-mono`
// (a mono sheet). Every theme declares its family THROUGH that hook
// (`--font-sans: var(--mono-font-sans, <the theme's own stack>)`, see flavors/one.css,
// flavors/_vega-base.css and the generated tokens.css), and no theme ever sets the hook
// itself, so it inherits from :root through any `.theme-*` class:
//   - sheet imported → that font, in every theme, and it stays across a theme switch;
//   - no sheet       → each theme's default (ONE: Poppins, the Basecoat styles: Geist);
//   - a sheet loaded or removed at runtime (a lazy import, a toggled <link>) → the page
//     switches font live, nothing else to call.
// Two sheets of the same kind: the one later in the cascade wins (same selector).
//
// `vite.config.ts` → `mono-emit-flavor-themes` emits the result into dist/ui/font/.
import { mkdirSync, readdirSync, readFileSync } from 'node:fs'
import path from 'node:path'
import { createGenerator } from 'unocss'
import presetWebFonts from '@unocss/preset-web-fonts'
import { createLocalFontProcessor } from '@unocss/preset-web-fonts/local'

/** The generic tail after the sheet's own family, per kind. */
const FALLBACK = {
  sans: 'ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji"',
  mono: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace',
}

/**
 * sheet name → presetWebFonts spec + the override hook it sets (`kind`: 'sans' →
 * `--mono-font-sans`, 'mono' → `--mono-font-mono`).
 *   poppins     — the ONE flavor's own family
 *   geist       — the Basecoat styles' own family (Basecoat names it "Geist Sans"; Google
 *                 Fonts serves it as "Geist", which is the family this sheet registers)
 *   geist-mono  — the Basecoat code font (`--font-mono`), read by the rich-text editor
 *   inter       — not a theme default; an override to pick
 */
export const FONT_SHEETS = {
  poppins: { spec: 'Poppins:400;500;600;700', kind: 'sans' },
  geist: { spec: 'Geist:400;500;600;700', kind: 'sans' },
  inter: { spec: 'Inter:400;500;600;700', kind: 'sans' },
  'geist-mono': { spec: 'Geist Mono:400;500', kind: 'mono' },
}

/** The override rule a sheet ends with. */
export function fontOverrideRule(family, kind) {
  return `:root {\n  --mono-font-${kind}: "${family}", ${FALLBACK[kind]};\n}\n`
}

/**
 * The font downloads, with retries — they run in parallel against fonts.gstatic.com,
 * and one connect timeout used to fail the whole library build.
 */
async function fetchFont(url) {
  for (let attempt = 1; ; attempt++) {
    try {
      const res = await fetch(url, { signal: AbortSignal.timeout(30_000) })
      if (!res.ok) throw new Error(`${res.status} ${res.statusText} — ${url}`)
      return res
    } catch (err) {
      if (attempt >= 4) throw err
      await new Promise((r) => setTimeout(r, 1000 * attempt))
    }
  }
}

/**
 * Build every sheet. Returns `{ css: { [fileName]: source }, files: { [fileName]: Buffer } }`
 * with names relative to dist/ui/ (`font/poppins.css`, `font/files/poppins-<hash>.woff2`).
 * Downloads are cached under `cacheRoot`, so a rebuild fetches nothing new.
 */
export async function buildFontSheets(cacheRoot) {
  const css = {}
  const files = {}
  for (const [name, { spec, kind }] of Object.entries(FONT_SHEETS)) {
    const dir = path.join(cacheRoot, name)
    mkdirSync(dir, { recursive: true })
    const uno = await createGenerator({
      presets: [
        presetWebFonts({
          fonts: { [name]: spec },
          processors: createLocalFontProcessor({
            fontAssetsDir: dir,
            fontServeBaseUrl: './files',
            fetch: fetchFont,
          }),
        }),
      ],
    })
    const { css: out } = await uno.generate('', { preflights: true })
    const faces = out.match(/@font-face\s*\{[^}]*\}/g) ?? []
    if (!faces.length) throw new Error(`font sheet "${name}": UnoCSS produced no @font-face`)
    const family = spec.split(':')[0]
    css[`font/${name}.css`] =
      `/* ${family} — self-hosted by @mono-lit/helper (UnoCSS presetWebFonts, local processor).\n` +
      `   import '@mono-lit/helper/ui/font/${name}.css'\n` +
      `   Importing it makes ${family} the ${kind} font of EVERY mono theme: it sets\n` +
      `   --mono-font-${kind}, which each theme's family reads first. Without it, each theme\n` +
      `   keeps its own default. */\n` +
      faces.join('\n') +
      '\n' +
      fontOverrideRule(family, kind)
    // Only the files this sheet references (the cache dir is per sheet, but be exact).
    for (const file of readdirSync(dir)) {
      if (faces.some((f) => f.includes(`./files/${file}`))) files[`font/files/${file}`] = readFileSync(path.join(dir, file))
    }
  }
  return { css, files }
}
