/**
 * Generate `src/composables/mdi-glyphs.ts` — the artwork a SHADOW build needs.
 *
 * The light builds paint `i-mdi-*` as a UnoCSS mask, which cannot reach inside a
 * shadow root (and `shadow-css.ts` deliberately excludes icon rules from utility
 * adoption). A shadow build therefore has to draw the glyph itself, and it must
 * be the SAME drawing, or the two builds show different icons for one prop.
 *
 * Source of truth: `@iconify-json/mdi` — the same package UnoCSS's presetIcons
 * resolves the light build's masks from, so the paths are identical by
 * construction. Re-run after changing `NAMES` (or the uno.config safelist):
 *
 *     node scripts/mdi-glyphs.mjs
 *     node scripts/mdi-glyphs.mjs --check   # CI: fails if the file is stale
 */
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { createRequire } from 'node:module'

const require_ = createRequire(import.meta.url)
const PKG = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const OUT = path.join(PKG, 'src/composables/mdi-glyphs.ts')

/**
 * Every glyph a component renders ITSELF (so the shadow build can draw it).
 * Keep in step with the `i-mdi-*` entries of `uno.config.ts`'s safelist — that
 * list is what the light build ships; this one is what the shadow build draws.
 */
const NAMES = [
  // file-upload — the dropzone prompt, and the icons `icon` demos pass
  'cloud-upload-outline',
  'cloud-upload',
  'folder-upload',
  // file-upload — getFileIcon()'s file-type thumbs
  'file-image',
  'file-pdf-box',
  'file-excel',
  'file-word',
  'zip-box',
  'file-video',
  'file-music',
  'file',
  // shared — the remove / clear affordance
  'close',
  // alert — the status icons its `icon` prop / demos use
  'information-outline',
  'check-circle-outline',
  'alert-outline',
  'alert-circle-outline',
  'bell-outline',
]

const icons = require_('@iconify-json/mdi/icons.json')
const W = icons.width ?? 24
const H = icons.height ?? 24

const entries = NAMES.map((name) => {
  const icon = icons.icons[name]
  if (!icon) throw new Error(`mdi has no icon "${name}"`)
  const body = icon.body.replace(/\s+/g, ' ').trim()
  const w = icon.width ?? W
  const h = icon.height ?? H
  if (w !== 24 || h !== 24) throw new Error(`"${name}" is ${w}x${h}; the template assumes 24x24`)
  return `  'i-mdi-${name}': '${body.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}',`
}).join('\n')

const out = `// GENERATED by scripts/mdi-glyphs.mjs — do not edit.
//
// The SVG body of every \`i-mdi-*\` glyph a mono component renders itself, taken
// from \`@iconify-json/mdi\` (the same source UnoCSS's presetIcons resolves the
// light build's masks from). A shadow build cannot use those masks — the page's
// icon CSS does not cross the shadow boundary — so it draws the identical path
// data inline instead, and one \`icon\` prop looks the same in both builds.
//
// Re-generate with \`node scripts/mdi-glyphs.mjs\` after editing its NAMES list.

/** \`i-mdi-<name>\` → the inner SVG markup of that glyph, on a 24x24 viewBox. */
export const MDI_GLYPHS: Readonly<Record<string, string>> = {
${entries}
}

/** The artwork for an \`i-mdi-*\` class, or \`undefined\` when it is not bundled. */
export function mdiGlyphBody(icon: string | undefined | null): string | undefined {
  if (!icon) return undefined
  return MDI_GLYPHS[icon.trim()]
}
`

if (process.argv.includes('--check')) {
  const current = fs.existsSync(OUT) ? fs.readFileSync(OUT, 'utf8').replace(/\r\n/g, '\n') : ''
  if (current !== out) {
    console.error('src/composables/mdi-glyphs.ts is stale — run `node scripts/mdi-glyphs.mjs`')
    process.exit(1)
  }
  console.log('mdi glyph map is current')
} else {
  fs.writeFileSync(OUT, out)
  console.log(`wrote ${path.relative(PKG, OUT)} (${NAMES.length} glyphs)`)
}
