/**
 * Generate `docs/ui/color.md` (repo root) from the resolved colour presets
 * (src/data/theme/presets.json through scripts/theme-build.mjs), so the page
 * can never disagree with the tokens the library ships.
 *
 *   node scripts/theme-docs.mjs           write the page
 *   node scripts/theme-docs.mjs --check   exit 1 if the committed page is stale
 *
 * `pnpm theme:build` runs this too. tests/perf/color-docs.spec.mjs runs --check.
 */
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { build, oklch } from './theme-build.mjs'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
// The docs site is the repo's top-level docs/ folder (root = packages/helper).
export const DOC = path.join(root, '..', '..', 'docs', 'ui', 'color.md')

const SECTIONS = [
  ['Brand', ['primary', 'primaryForeground', 'secondary', 'secondaryForeground', 'accent', 'accentForeground', 'ring']],
  ['Status', ['destructive', 'destructiveForeground', 'success', 'successForeground', 'warning', 'warningForeground', 'info', 'infoForeground']],
  ['Extended', ['teal', 'tealForeground', 'purple', 'purpleForeground', 'neutral', 'neutralForeground', 'dark', 'darkForeground']],
  ['Surfaces, ink and lines', ['background', 'foreground', 'card', 'cardForeground', 'popover', 'popoverForeground', 'muted', 'mutedForeground', 'border', 'input']],
  ['Charts', ['chart1', 'chart2', 'chart3', 'chart4', 'chart5']],
]

const kebab = (s) => s.replace(/([A-Z])/g, '-$1').replace(/(\d)/g, '-$1').toLowerCase()

function cell(value) {
  const v = oklch(value)
  return `<div class="color-cell"><span class="color-chip" style="background:${v}"></span><code>${v}</code></div>`
}

export function render() {
  const { resolved, names } = build()
  const presets = JSON.parse(fs.readFileSync(path.join(root, 'src', 'data', 'theme', 'presets.json'), 'utf8'))
  const modes = (n) => (resolved[n].noDark ? ['light'] : ['light', 'dark'])
  const cols = names.reduce((sum, n) => sum + modes(n).length, 0)
  const classes = names.map((n) => `\`theme-color-${n}\``).join(', ')
  let out = `<!-- GENERATED by scripts/theme-docs.mjs from src/data/theme/presets.json — edit the JSON, then \`pnpm theme:build\`. -->
# Color

@mono-lit/helper paints with Basecoat's token set — \`--background\`, \`--primary\`, \`--destructive\`, \`--ring\` … in OKLCH, with a \`.dark\` twin for every one — plus seven extension roles Basecoat does not have: \`success\`, \`warning\`, \`info\`, \`teal\`, \`purple\`, \`neutral\` and \`dark\`, each with its own \`-foreground\` ink. This page lists every value the library ships, per colour preset, in both modes.

Pick a palette with a class on \`<html>\` (or the [theme API](./theme#vue-api)): ${classes}. **Basecoat is the default** — it is what \`:root\` already declares, so its class is optional. Dark mode is \`class="dark"\` on \`<html>\` (or \`<body>\`, or a \`.mono-theme\` wrapper).

The role names below are also what a component's \`color\` prop accepts (\`danger\` paints \`--destructive\`).

`
  const head = `<div class="color-grid" style="--color-grid-cols: ${cols}">
<div class="color-grid__corner"></div>
${names.map((n) => modes(n).map((m) => `<div class="color-grid__theme">${presets[n].displayName} · ${m}</div>`).join('\n')).join('\n')}
`
  for (const [title, keys] of SECTIONS) {
    out += `## ${title}\n\n${head}`
    for (const key of keys) {
      out += `<div class="color-grid__role">--${kebab(key)}</div>\n`
      for (const n of names) for (const m of modes(n)) out += `${cell(resolved[n][m][key])}\n`
    }
    out += `</div>\n\n`
    if (title === 'Brand') {
      out += `\`secondary\` and \`accent\` follow shadcn's meaning: \`secondary\` is a muted **surface** (a grey button, a soft chip), \`accent\` is the hover surface. Neither is a second brand hue — the blue that used to sit in \`secondary\` is \`info\`.\n\n`
    }
  }
  const lightOnly = names.filter((n) => resolved[n].noDark)
  if (lightOnly.length) {
    out += `::: info Light only\n${lightOnly.map((n) => `**${presets[n].displayName}**`).join(', ')} has no dark palette: under \`html.dark\` it keeps its light values (and light mode tokens), so a page can use the dark toggle everywhere else while this preset stays as designed.\n:::\n\n`
  }
  const derived = names.filter((n) => resolved[n].derivedDark)
  if (derived.length) {
    out += `::: warning Derived dark palettes\nThe dark values of ${derived.map((n) => `**${presets[n].displayName}**`).join(', ')} are derived from the light palette with Basecoat's own light→dark deltas (\`scripts/theme-build.mjs\`), not hand-tuned. Review them here and pin explicit values in \`presets.json\` where they read wrong.\n:::\n\n`
  }
  out += `## Using the colors

Set a role with the \`color\` prop, or read the tokens directly in your own CSS:

\`\`\`css
.my-panel {
  background: var(--card);
  color: var(--card-foreground);
  border: 1px solid var(--border);
}
.my-panel--flagged {
  background: color-mix(in oklab, var(--destructive) 10%, transparent);
  color: var(--destructive);
}
\`\`\`

Alpha is \`color-mix(in oklab, var(--x) N%, transparent)\` — the same recipe every ported component uses. (The pre-Basecoat \`--theme-<slot>-rgb\` triplets still exist in \`ui/theme/legacy.css\` until 3.0.)

A \`color\` prop also takes a raw CSS colour, and works out a readable ink for it automatically:

\`\`\`html
<mono-sidebar color="#7c3aed"></mono-sidebar>
\`\`\`

To re-skin globally, override the tokens — a [TweakCN](https://tweakcn.com) theme pastes in as-is, and the extension roles follow the same shape:

\`\`\`css
:root {
  --primary: oklch(0.541 0.247 293.01);
  --primary-foreground: oklch(1 0 0);
}
.dark {
  --primary: oklch(0.7 0.174 293.05);
}
\`\`\`

## ONE's pillar colors

The ONE palette carries five extra brand tokens for the EJI pillars. No mono component reads them; they exist for application code that needs those colours by name.

<div class="color-list">
${Object.entries(presets.one.legacy).filter(([k]) => k.startsWith('--theme-pillar-')).map(([k, v]) => `<div class="color-cell"><span class="color-chip" style="background:${v}"></span><code>${v}</code><span class="color-name">${k}</span></div>`).join('\n')}
</div>

---

For the control ladder, radii, shadows and everything that is not a colour, see [Theme](./theme).
`
  return out
}

export function check() {
  const have = fs.existsSync(DOC) ? fs.readFileSync(DOC, 'utf8').replace(/\r\n?/g, '\n') : ''
  return have === render()
}

const isMain = process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)
if (isMain) {
  if (process.argv.includes('--check')) {
    if (!check()) { console.error('ui/color.md is stale — run `pnpm theme:build`'); process.exit(1) }
    console.log('ui/color.md is current')
  } else {
    fs.writeFileSync(DOC, render())
    console.log(`wrote ${path.relative(root, DOC)}`)
  }
}
