/**
 * Generate the token layer from `src/data/theme/presets.json` and the vendored
 * Basecoat `base.css`:
 *
 *   src/data/theme/generated/tokens.css    :root / .dark defaults (Basecoat's own palette), Tailwind engine subset (--mono-*),
 *                                          mode tokens, mono's control scale
 *   src/data/theme/generated/presets.css   .theme-color-<name> light + dark blocks
 *   src/data/theme/generated/legacy.css    the pre-Basecoat --theme-* vocabulary, alive
 *                                          until 3.0 (aliases where value-identical, the
 *                                          old literal otherwise, -rgb triplets per mode)
 *
 *   node scripts/theme-build.mjs           write
 *   node scripts/theme-build.mjs --check   exit 1 if the committed output is stale
 *
 * Two CSS facts every emitted rule respects:
 *  1. A custom property whose value contains var() is substituted on the element
 *     that DECLARES it. Declared only on :root it goes stale as soon as a
 *     `.theme-color-*` or `.dark` class on <body> overrides the base token. So
 *     every var()-bearing token is emitted on the SCOPES rule below, which
 *     matches every element a preset/mode class can land on.
 *  2. Basecoat's `dark:` variants compile to `&:is(html.dark *)`, which cannot
 *     match inside a shadow root. Mode differences therefore travel only as
 *     inherited custom properties (`--mono-mode-*`), never as selectors.
 */
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import postcss from 'postcss'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const THEME_DIR = path.join(root, 'src', 'data', 'theme')
const OUT_DIR = path.join(THEME_DIR, 'generated')
const PRESETS = path.join(THEME_DIR, 'presets.json')
const VENDOR_BASE = path.join(THEME_DIR, 'vendor', 'basecoat', 'base', 'base.css')

/** The palette :root carries. */
const DEFAULT_PRESET = 'one'

const HEADER = (what) =>
  `/* GENERATED by scripts/theme-build.mjs — ${what}.\n   Edit src/data/theme/presets.json (or the generator) and run \`pnpm theme:build\`. */\n`

/**
 * Where the mode class counts. NOT a bare `.dark`: `.mono-button.dark`,
 * `.mono-card.dark`, `.mono-sidebar.dark` … are COLOUR classes (the `dark`
 * palette slot), and a bare `.dark { --primary: … }` would flip every token
 * under them. `html` is where Basecoat / VitePress / applyMode() put it; `body`
 * and a `.mono-theme` wrapper cover the "dark section" pattern.
 */
const DARK_ROOT = ':is(html, body, .mono-theme).dark'
/** Elements a preset / mode class can be placed on — where var()-bearing tokens must re-derive. */
const SCOPES = `:where(:root, ${DARK_ROOT}, [class*="theme-"], .mono-theme)`
const DARK_SCOPES = `:where(${DARK_ROOT}, ${DARK_ROOT} [class*="theme-"], ${DARK_ROOT} .mono-theme)`

/* ───────────────────────────── colour math ────────────────────────────── */

function parse(value) {
  const v = String(value).trim()
  let m = /^#([0-9a-f]{6})([0-9a-f]{2})?$/i.exec(v)
  if (m) {
    const n = parseInt(m[1], 16)
    return { r: (n >> 16) & 255, g: (n >> 8) & 255, b: n & 255, a: m[2] ? parseInt(m[2], 16) / 255 : 1 }
  }
  m = /^#([0-9a-f]{3})$/i.exec(v)
  if (m) {
    const [r, g, b] = m[1].split('').map((c) => parseInt(c + c, 16))
    return { r, g, b, a: 1 }
  }
  m = /^rgba?\(\s*([\d.]+)\s*,\s*([\d.]+)\s*,\s*([\d.]+)\s*(?:,\s*([\d.]+))?\s*\)$/i.exec(v)
  if (m) return { r: +m[1], g: +m[2], b: +m[3], a: m[4] === undefined ? 1 : +m[4] }
  m = /^oklch\(\s*([\d.]+)\s+([\d.]+)\s+([\d.]+)\s*(?:\/\s*([\d.]+)(%?))?\s*\)$/i.exec(v)
  if (m) {
    const a = m[4] === undefined ? 1 : m[5] ? +m[4] / 100 : +m[4]
    return { ...oklchToRgb(+m[1], +m[2], +m[3]), a }
  }
  throw new Error(`theme-build: cannot parse colour "${value}"`)
}

const lin = (c) => ((c /= 255) <= 0.04045 ? c / 12.92 : ((c + 0.055) / 1.055) ** 2.4)
const gam = (c) => 255 * (c <= 0.0031308 ? 12.92 * c : 1.055 * c ** (1 / 2.4) - 0.055)

function rgbToOklab({ r, g, b }) {
  const [lr, lg, lb] = [lin(r), lin(g), lin(b)]
  const l = Math.cbrt(0.4122214708 * lr + 0.5363325363 * lg + 0.0514459929 * lb)
  const m = Math.cbrt(0.2119034982 * lr + 0.6806995451 * lg + 0.1073969566 * lb)
  const s = Math.cbrt(0.0883024619 * lr + 0.2817188376 * lg + 0.6299787005 * lb)
  return {
    L: 0.2104542553 * l + 0.793617785 * m - 0.0040720468 * s,
    a: 1.9779984951 * l - 2.428592205 * m + 0.4505937099 * s,
    b: 0.0259040371 * l + 0.7827717662 * m - 0.808675766 * s,
  }
}

function oklabToLinear({ L, a, b }) {
  const l = (L + 0.3963377774 * a + 0.2158037573 * b) ** 3
  const m = (L - 0.1055613458 * a - 0.0638541728 * b) ** 3
  const s = (L - 0.0894841775 * a - 1.291485548 * b) ** 3
  return [
    4.0767416621 * l - 3.3077115913 * m + 0.2309699292 * s,
    -1.2684380046 * l + 2.6097574011 * m - 0.3413193965 * s,
    -0.0041960863 * l - 0.7034186147 * m + 1.707614701 * s,
  ]
}

function rgbToOklch(rgb) {
  const { L, a, b } = rgbToOklab(rgb)
  const C = Math.hypot(a, b)
  let H = (Math.atan2(b, a) * 180) / Math.PI
  if (H < 0) H += 360
  return { L, C: C < 1e-4 ? 0 : C, H: C < 1e-4 ? 0 : H }
}

function oklchToRgb(L, C, H) {
  const rad = (H * Math.PI) / 180
  const [r, g, b] = oklabToLinear({ L, a: C * Math.cos(rad), b: C * Math.sin(rad) })
  return { r: gam(r), g: gam(g), b: gam(b) }
}

function inGamut({ r, g, b }) {
  return [r, g, b].every((c) => c >= -0.5 && c <= 255.5)
}

/** Reduce chroma until the colour fits sRGB (Basecoat's own values are all in gamut). */
function clampChroma(L, C, H) {
  if (inGamut(oklchToRgb(L, C, H))) return C
  let lo = 0
  let hi = C
  for (let i = 0; i < 24; i++) {
    const mid = (lo + hi) / 2
    if (inGamut(oklchToRgb(L, mid, H))) lo = mid
    else hi = mid
  }
  return lo
}

const round8 = ({ r, g, b }) => [r, g, b].map((c) => Math.min(255, Math.max(0, Math.round(c))))

/**
 * `oklch(L C H[ / A%])` for a colour, at the fewest decimals that round-trip to
 * the same 8-bit sRGB triple the author wrote — so the port changes the notation,
 * not the pixel.
 */
export function oklch(value) {
  // Already OKLCH (the vendor preset): verbatim — Basecoat's chroma can sit just outside sRGB.
  if (String(value).trim().toLowerCase().startsWith('oklch(')) return String(value).trim()
  const rgb = parse(value)
  const { L, C, H } = rgbToOklch(rgb)
  const want = round8(rgb).join()
  for (let p = 3; p <= 6; p++) {
    const s = { L: +L.toFixed(p), C: +C.toFixed(p), H: +H.toFixed(Math.max(2, p - 1)) }
    if (round8(oklchToRgb(s.L, s.C, s.H)).join() === want) return fmt(s, rgb.a)
  }
  throw new Error(`theme-build: ${value} does not round-trip through oklch`)
}

function fmt({ L, C, H }, a = 1) {
  const alpha = a < 1 ? ` / ${Math.round(a * 1000) / 10}%` : ''
  return `oklch(${trim(L)} ${trim(C)} ${trim(H)}${alpha})`
}
const trim = (n) => String(+n)

function toHex({ r, g, b }) {
  return '#' + round8({ r, g, b }).map((c) => c.toString(16).padStart(2, '0')).join('')
}

/** Solid colour of `fg` painted at its alpha over `bg`. */
function over(fg, bg) {
  const f = parse(fg)
  const b = parse(bg)
  const mix = (x, y) => x * f.a + y * (1 - f.a)
  return toHex({ r: mix(f.r, b.r), g: mix(f.g, b.g), b: mix(f.b, b.b) })
}

function luminance({ r, g, b }) {
  const f = (v) => ((v /= 255) <= 0.03928 ? v / 12.92 : ((v + 0.055) / 1.055) ** 2.4)
  return 0.2126 * f(r) + 0.7152 * f(g) + 0.0722 * f(b)
}
function contrast(a, b) {
  const [hi, lo] = [luminance(a), luminance(b)].sort((x, y) => y - x)
  return (hi + 0.05) / (lo + 0.05)
}

const INK_LIGHT = '#ffffff'
const INK_DARK = 'rgba(0, 0, 0, 0.87)'
/** The same rule as `readableInk` in src/composables/color.ts. */
function ink(bg) {
  const c = parse(bg)
  const white = { r: 255, g: 255, b: 255 }
  const darkOver = { r: c.r * 0.13, g: c.g * 0.13, b: c.b * 0.13 }
  return contrast(c, white) >= contrast(c, darkOver) ? INK_LIGHT : INK_DARK
}

/** New colour at the primary's hue with the given lightness / chroma (gamut-clamped). */
function tone(value, { L, C, Cmax }) {
  const o = rgbToOklch(parse(value))
  const c = clampChroma(L, Math.min(C ?? o.C, Cmax ?? Infinity), o.H)
  return toHex(oklchToRgb(L, c, o.H))
}

/* ─────────────────────────── palette assembly ─────────────────────────── */

const ROLES = ['success', 'warning', 'info', 'teal', 'purple', 'neutral', 'dark']

/** The shadcn set, in base.css order, plus our roles. */
const SEMANTIC = [
  'background', 'foreground', 'card', 'cardForeground', 'popover', 'popoverForeground',
  'primary', 'primaryForeground', 'secondary', 'secondaryForeground', 'muted', 'mutedForeground',
  'accent', 'accentForeground', 'destructive', 'destructiveForeground', 'border', 'input', 'ring',
  'chart1', 'chart2', 'chart3', 'chart4', 'chart5',
]
const SIDEBAR = ['sidebar', 'sidebarForeground', 'sidebarPrimary', 'sidebarPrimaryForeground',
  'sidebarAccent', 'sidebarAccentForeground', 'sidebarBorder', 'sidebarRing']

const kebab = (s) => s.replace(/([A-Z])/g, '-$1').replace(/(\d)/g, '-$1').toLowerCase()
const cssName = (key) => `--${kebab(key)}`

/** Fill every derivable slot of a light palette. */
function completeLight(p) {
  const o = { ...p }
  o.card ??= '#ffffff'
  o.popover ??= o.card
  o.muted ??= o.card
  o.secondary ??= o.muted
  o.accent ??= o.muted
  o.input ??= o.border
  o.ring ??= o.primary
  o.cardForeground ??= o.foreground
  o.popoverForeground ??= o.foreground
  o.secondaryForeground ??= o.foreground
  o.accentForeground ??= o.foreground
  o.mutedForeground ??= over(`rgba(${round8(parse(o.foreground)).join(', ')}, 0.6)`, o.background)
  // Light mode keeps the pre-Basecoat convention: white ink on every saturated fill,
  // contrast-picked only for the three slots that were always too light for it.
  for (const k of ['primary', 'destructive', ...ROLES]) {
    o[`${k}Foreground`] ??= ['warning', 'teal', 'neutral'].includes(k) ? ink(o[k]) : INK_LIGHT
  }
  for (let i = 1; i <= 5; i++) o[`chart${i}`] ??= tone(o.primary, { L: 0.86 - (i - 1) * 0.125, Cmax: 0.16 })
  return o
}

/**
 * Basecoat's own light→dark deltas (base.css), applied to a branded palette:
 * neutrals drop to Basecoat's lightness steps keeping a whisper of the brand
 * hue; the brand and status hues are lifted so they read on a dark ground.
 */
function deriveDark(l) {
  const d = {}
  d.background = tone(l.background, { L: 0.145, Cmax: 0.02 })
  d.foreground = tone(l.foreground, { L: 0.985, Cmax: 0.01 })
  d.card = tone(l.background, { L: 0.205, Cmax: 0.02 })
  d.popover = d.card
  d.muted = tone(l.background, { L: 0.269, Cmax: 0.02 })
  d.secondary = d.muted
  d.accent = tone(l.background, { L: 0.371, Cmax: 0.02 })
  d.mutedForeground = tone(l.foreground, { L: 0.708, Cmax: 0.02 })
  d.border = 'rgba(255, 255, 255, 0.10)'
  d.input = 'rgba(255, 255, 255, 0.15)'
  d.primary = tone(l.primary, { L: Math.max(rgbToOklch(parse(l.primary)).L, 0.75) })
  d.ring = tone(l.ring, { L: 0.556, Cmax: 0.12 })
  d.destructive = tone(l.destructive, { L: Math.max(rgbToOklch(parse(l.destructive)).L, 0.704) })
  for (const k of ROLES) {
    const L = rgbToOklch(parse(l[k])).L
    // `dark` flips like `primary` does: it is the strong neutral AGAINST the page,
    // and as outline / text ink a near-black on a near-black ground is unreadable
    // (a solid one read as disabled). `neutral` keeps its mid grey with WHITE ink —
    // lifting it to L 0.708 with dark ink made it a dead ringer for a disabled
    // primary (which is exactly that grey at 50% opacity).
    d[k] = k === 'dark' ? tone(l[k], { L: 0.87, Cmax: 0.02 })
      : k === 'neutral' ? tone(l[k], { L: Math.min(Math.max(L, 0.55), 0.6) })
      : tone(l[k], { L: Math.max(L, 0.7) })
  }
  return d
}

function completeDark(light, dark) {
  const base = deriveDark(light)
  const o = { ...base, ...dark }
  o.popover ??= o.card
  o.cardForeground ??= o.foreground
  o.popoverForeground ??= o.foreground
  o.secondaryForeground ??= o.foreground
  o.accentForeground ??= o.foreground
  // neutral keeps white ink in dark mode (see deriveDark); the rest are contrast-picked
  o.neutralForeground ??= INK_LIGHT
  for (const k of ['primary', 'destructive', ...ROLES]) o[`${k}Foreground`] ??= ink(o[k])
  for (let i = 1; i <= 5; i++) o[`chart${i}`] ??= tone(o.primary, { L: 0.86 - (i - 1) * 0.125, Cmax: 0.16 })
  return o
}

/* ───────────────────────── vendor base.css reader ─────────────────────── */

function readVendorBase() {
  const css = postcss.parse(fs.readFileSync(VENDOR_BASE, 'utf8'))
  const blocks = { ':root': {}, '.dark': {}, '@theme': {} }
  css.walk((node) => {
    if (node.type === 'rule' && blocks[node.selector]) {
      node.each((d) => { if (d.type === 'decl' && d.prop.startsWith('--')) blocks[node.selector][d.prop] = d.value })
    } else if (node.type === 'atrule' && node.name === 'theme') {
      node.each((d) => { if (d.type === 'decl') blocks['@theme'][d.prop] = d.value })
    }
  })
  return blocks
}

/* ────────────────────────────── emission ──────────────────────────────── */

function decl(name, value) {
  return `  ${name}: ${value};\n`
}
function rule(selector, body) {
  return body.trim() ? `${selector} {\n${body}}\n` : ''
}

const ENGINE = [
  // Tailwind v4 theme values the compiled Basecoat rules read, prefixed so a
  // consumer's own Tailwind / UnoCSS `--spacing` cannot reflow our components.
  ['--mono-spacing', '0.25rem'],
  ['--mono-text-xs', '0.75rem'], ['--mono-text-xs--lh', 'calc(1 / 0.75)'],
  ['--mono-text-sm', '0.875rem'], ['--mono-text-sm--lh', 'calc(1.25 / 0.875)'],
  ['--mono-text-base', '1rem'], ['--mono-text-base--lh', 'calc(1.5 / 1)'],
  ['--mono-text-lg', '1.125rem'], ['--mono-text-lg--lh', 'calc(1.75 / 1.125)'],
  ['--mono-text-xl', '1.25rem'], ['--mono-text-xl--lh', 'calc(1.75 / 1.25)'],
  ['--mono-font-weight-normal', '400'], ['--mono-font-weight-medium', '500'],
  ['--mono-font-weight-semibold', '600'], ['--mono-font-weight-bold', '700'],
  ['--mono-tracking-tight', '-0.025em'], ['--mono-tracking-wide', '0.025em'], ['--mono-tracking-wider', '0.05em'], ['--mono-tracking-widest', '0.1em'],
  ['--mono-leading-none', '1'], ['--mono-leading-snug', '1.375'],
  ['--mono-leading-normal', '1.5'], ['--mono-leading-relaxed', '1.625'],
  ['--mono-radius-2xl', '1rem'], ['--mono-radius-3xl', '1.5rem'], ['--mono-radius-4xl', '2rem'], ['--mono-radius-full', '9999px'],
  ['--mono-shadow-none', '0 0 #0000'],
  ['--mono-shadow-xs', '0 1px 2px 0 rgb(0 0 0 / 0.05)'],
  ['--mono-shadow-sm', '0 1px 3px 0 rgb(0 0 0 / 0.1), 0 1px 2px -1px rgb(0 0 0 / 0.1)'],
  ['--mono-shadow-md', '0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)'],
  ['--mono-shadow-lg', '0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)'],
  ['--mono-shadow-xl', '0 20px 25px -5px rgb(0 0 0 / 0.1), 0 8px 10px -6px rgb(0 0 0 / 0.1)'],
  ['--mono-shadow-2xl', '0 25px 50px -12px rgb(0 0 0 / 0.25)'],
  ['--mono-ease', 'cubic-bezier(0.4, 0, 0.2, 1)'], ['--mono-ease-out', 'cubic-bezier(0, 0, 0.2, 1)'],
  ['--mono-duration', '150ms'], ['--mono-duration-fast', '100ms'], ['--mono-duration-slow', '200ms'],
  ['--mono-animate-pulse', 'mono-pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite'],
  ['--mono-blur-xs', '4px'],
  ['--mono-container-xs', '20rem'], ['--mono-container-sm', '24rem'], ['--mono-container-md', '28rem'],
  ['--mono-container-lg', '32rem'], ['--mono-container-xl', '36rem'], ['--mono-container-2xl', '42rem'],
  ['--mono-border-width', '1px'],
  ['--mono-ring-width', '3px'],
  ['--mono-ring-alpha', '50%'],
]
const ENGINE_DERIVED = [
  ['--mono-radius-sm', 'calc(var(--radius) - 4px)'],
  ['--mono-radius-md', 'calc(var(--radius) - 2px)'],
  ['--mono-radius-lg', 'var(--radius)'],
  ['--mono-radius-xl', 'calc(var(--radius) + 4px)'],
  ['--mono-ring-color', 'color-mix(in oklab, var(--ring) var(--mono-ring-alpha), transparent)'],
  ['--mono-ring', '0 0 0 var(--mono-ring-width) var(--mono-ring-color)'],
]

const SCALE = [
  // mono's own scale — the painted outer height of every control (button, input,
  // select, tag-input, date, textarea rows). md = Basecoat's h-9.
  ['--mono-control-height-xs', '1.5rem'], ['--mono-control-height-sm', '2rem'],
  ['--mono-control-height-md', '2.25rem'], ['--mono-control-height-lg', '2.5rem'],
  ['--mono-control-height-xl', '2.75rem'], ['--mono-control-height-xxl', '3rem'],
  ['--mono-control-font-xs', '0.75rem'], ['--mono-control-font-sm', '0.875rem'],
  ['--mono-control-font-md', '0.875rem'], ['--mono-control-font-lg', '0.875rem'],
  ['--mono-control-font-xl', '1rem'], ['--mono-control-font-xxl', '1.125rem'],
  ['--mono-label-font-size', '0.875rem'], ['--mono-label-font-weight', '500'],
  ['--mono-message-font-size', '0.875rem'], ['--mono-option-font-size', '0.875rem'],
  ['--mono-title-font-xs', '0.75rem'], ['--mono-title-font-sm', '0.875rem'],
  ['--mono-title-font-md', '1rem'], ['--mono-title-font-lg', '1.125rem'],
  ['--mono-title-font-xl', '1.25rem'], ['--mono-title-font-xxl', '1.5rem'],
  ['--mono-title-font-weight', '500'], ['--mono-title-line-height', '1'],
  ['--mono-subtitle-font-xs', '0.75rem'], ['--mono-subtitle-font-sm', '0.75rem'],
  ['--mono-subtitle-font-md', '0.875rem'], ['--mono-subtitle-font-lg', '0.875rem'],
  ['--mono-subtitle-font-xl', '1rem'], ['--mono-subtitle-font-xxl', '1.125rem'],
  ['--mono-subtitle-font-weight', '400'], ['--mono-subtitle-line-height', '1.5'],
  ['--mono-icon-sm', '0.875rem'], ['--mono-icon-md', '1.25rem'], ['--mono-icon-lg', '2rem'],
]

/**
 * Mode tokens — every `dark:` delta in styles/vega.css expressed as a value that
 * inherits into shadow roots. [name, light, dark]; `var()`-bearing entries land on
 * the SCOPES rules, literals on :root / .dark.
 */
const MODE = [
  ['--mono-mode-tint', '10%', '20%'],
  ['--mono-mode-tint-hover', '20%', '30%'],
  ['--mono-mode-checked-bg', '5%', '10%'],
  ['--mono-mode-checked-border', '30%', '20%'],
  ['--mono-mode-surface', 'transparent', 'color-mix(in oklab, var(--input) 30%, transparent)'],
  ['--mono-mode-surface-hover', 'var(--muted)', 'color-mix(in oklab, var(--input) 50%, transparent)'],
  ['--mono-mode-outline-bg', 'var(--background)', 'color-mix(in oklab, var(--input) 30%, transparent)'],
  ['--mono-mode-surface-strong', 'var(--input)', 'color-mix(in oklab, var(--input) 80%, transparent)'],
  // a field with NO light hover but `dark:hover:bg-input/50` (select / combobox triggers)
  ['--mono-mode-field-hover-bg', 'var(--mono-mode-surface)', 'color-mix(in oklab, var(--input) 50%, transparent)'],
  ['--mono-mode-outline-border', 'var(--border)', 'var(--input)'],
  ['--mono-mode-invalid-border', 'var(--destructive)', 'color-mix(in oklab, var(--destructive) 50%, transparent)'],
  ['--mono-mode-invalid-ring', 'color-mix(in oklab, var(--destructive) 20%, transparent)', 'color-mix(in oklab, var(--destructive) 40%, transparent)'],
  // the same two alphas for a NON-destructive state (mono's valid / warning): border x/100 dark x/50, ring x/20 dark x/40
  ['--mono-mode-state-border-alpha', '100%', '50%'],
  ['--mono-mode-state-ring-alpha', '20%', '40%'],
  ['--mono-mode-ghost-hover', 'var(--muted)', 'color-mix(in oklab, var(--muted) 50%, transparent)'],
  ['--mono-mode-tab-inactive-fg', 'color-mix(in oklab, var(--foreground) 60%, transparent)', 'var(--muted-foreground)'],
  ['--mono-mode-tab-active-bg', 'var(--background)', 'color-mix(in oklab, var(--input) 30%, transparent)'],
  ['--mono-mode-tab-active-border', 'transparent', 'var(--input)'],
  ['--mono-mode-switch-thumb', 'var(--background)', 'var(--foreground)'],
  ['--mono-mode-switch-thumb-checked', 'var(--background)', 'var(--primary-foreground)'],
  ['--mono-mode-backdrop', 'color-mix(in oklab, black 10%, transparent)', 'color-mix(in oklab, black 10%, transparent)'],
]
const hasVar = (v) => /var\(|color-mix\(/.test(v)

const SIDEBAR_DERIVED = [
  ['--sidebar', 'var(--card)'], ['--sidebar-foreground', 'var(--foreground)'],
  ['--sidebar-primary', 'var(--primary)'], ['--sidebar-primary-foreground', 'var(--primary-foreground)'],
  ['--sidebar-accent', 'var(--accent)'], ['--sidebar-accent-foreground', 'var(--accent-foreground)'],
  ['--sidebar-border', 'var(--border)'], ['--sidebar-ring', 'var(--ring)'],
]

/** Colour tokens of one mode as `--name: oklch(...)` lines. */
function paletteDecls(p, keys) {
  let out = ''
  for (const k of keys) if (p[k] !== undefined) out += decl(cssName(k), oklch(p[k]))
  for (const k of ROLES) {
    out += decl(`--${k}`, oklch(p[k]))
    out += decl(`--${k}-foreground`, oklch(p[`${k}Foreground`]))
  }
  return out
}

/* ───────────────────────────── legacy layer ───────────────────────────── */

/** old slot → new token, when the two are the same colour. `secondary`/`accent` never alias (meaning changed). */
const LEGACY_ALIAS = {
  primary: 'primary', background: 'background', text: 'foreground', border: 'border',
  surface: 'card', 'surface-soft': 'muted', danger: 'destructive',
  success: 'success', warning: 'warning', info: 'info', teal: 'teal', purple: 'purple',
  neutral: 'neutral', dark: 'dark',
}
const LEGACY_SLOTS = ['primary', 'secondary', 'accent', 'background', 'text', 'border', 'success',
  'danger', 'warning', 'info', 'teal', 'purple', 'neutral', 'dark', 'surface', 'surface-soft']
const RGB_SLOTS = LEGACY_SLOTS.filter((s) => !['surface', 'surface-soft'].includes(s))
const MONO_RGB = ['primary', 'secondary', 'success', 'danger', 'warning', 'info', 'neutral']
const CONTRAST_SLOTS = ['primary', 'success', 'danger', 'warning', 'info', 'teal', 'purple', 'neutral', 'dark']

/** The pre-Basecoat :root literals that are NOT colours — verbatim, until 3.0. */
const LEGACY_ROOT_LITERALS = `
  --theme-radius-xs: 0.25rem;
  --theme-radius-sm: 0.5rem;
  --theme-radius-md: 0.625rem;
  --theme-radius-lg: 0.75rem;
  --theme-radius-xl: 0.875rem;
  --theme-radius-2xl: 1.25rem;
  --theme-radius-full: 9999px;
  --theme-elev-0: none;
  --theme-elev-1: 0 1px 2px rgba(15, 23, 42, 0.06);
  --theme-elev-2: 0 3px 12px rgba(0, 0, 0, 0.08), 0 1px 2px rgba(15, 23, 42, 0.06);
  --theme-elev-3: 0 5px 20px rgba(0, 0, 0, 0.12), 0 1px 2px rgba(15, 23, 42, 0.06);
  --theme-elev-4: 0 10px 15px rgba(0, 0, 0, 0.10), 0 1px 2px rgba(15, 23, 42, 0.06);
  --theme-elev-5: 0 14px 28px rgba(0, 0, 0, 0.12), 0 1px 2px rgba(15, 23, 42, 0.06);
  --theme-motion-standard: cubic-bezier(0.25, 0.1, 0.25, 1);
  --theme-motion-emphasized: cubic-bezier(0.05, 0.7, 0.1, 1);
  --theme-duration-fast: 150ms;
  --theme-duration-base: 180ms;
  --theme-duration-slow: 200ms;
  --theme-space-1: 0.25rem;
  --theme-space-2: 0.5rem;
  --theme-space-3: 0.75rem;
  --theme-space-4: 1rem;
  --theme-space-5: 1.5rem;
  --theme-space-6: 2rem;
  --theme-font-family: system-ui, -apple-system, "Segoe UI", Roboto, sans-serif;
  --theme-font-weight-regular: 400;
  --theme-font-weight-medium: 500;
  --theme-font-weight-semibold: 600;
  --theme-font-weight-bold: 700;
  --theme-font-size-xs: 0.75rem;
  --theme-font-size-sm: 0.875rem;
  --theme-font-size-md: 1rem;
  --theme-font-size-lg: 1.125rem;
  --theme-font-size-xl: 1.25rem;
  --theme-line-height-tight: 1.2;
  --theme-line-height-base: 1.5;
  --theme-letter-spacing-button: 0;
  --theme-control-font-xs: 0.7rem;
  --theme-control-font-sm: 0.76rem;
  --theme-control-font-md: 0.8rem;
  --theme-control-font-lg: 0.84rem;
  --theme-control-font-xl: 0.9rem;
  --theme-control-font-xxl: 0.94rem;
  --theme-label-font-size: 0.76rem;
  --theme-message-font-size: 0.78rem;
  --theme-option-font-size: 0.84rem;
  --theme-title-font-xs: 0.74rem;
  --theme-title-font-sm: 0.78rem;
  --theme-title-font-md: 0.82rem;
  --theme-title-font-lg: 0.9rem;
  --theme-title-font-xl: 1rem;
  --theme-title-font-xxl: 1.1rem;
  --theme-title-line-height: 1.3;
  --theme-subtitle-font-xs: 0.66rem;
  --theme-subtitle-font-sm: 0.7rem;
  --theme-subtitle-font-md: 0.74rem;
  --theme-subtitle-font-lg: 0.8rem;
  --theme-subtitle-font-xl: 0.9rem;
  --theme-subtitle-font-xxl: 1rem;
  --theme-subtitle-line-height: 1.5;
  --theme-border-width: 1.5px;
  --theme-focus-ring-offset: 0;
`

/** The pre-Basecoat :root formulas — var()-bearing, so they live on the SCOPES rule. */
const LEGACY_ROOT_DERIVED = `
  --theme-control-height-xs: var(--mono-control-height-xs);
  --theme-control-height-sm: var(--mono-control-height-sm);
  --theme-control-height-md: var(--mono-control-height-md);
  --theme-control-height-lg: var(--mono-control-height-lg);
  --theme-control-height-xl: var(--mono-control-height-xl);
  --theme-control-height-xxl: var(--mono-control-height-xxl);
  --theme-label-font-weight: var(--theme-font-weight-bold);
  --theme-title-font-weight: var(--theme-font-weight-bold);
  --theme-subtitle-font-weight: var(--theme-font-weight-regular);
  --theme-focus-ring: 0 0 0 3px rgba(var(--theme-primary-rgb), 0.14);
  --theme-primary-light: color-mix(in srgb, var(--theme-primary) 60%, white);
  --theme-primary-dark: color-mix(in srgb, var(--theme-primary) 80%, black);
  --theme-secondary-light: color-mix(in srgb, var(--theme-secondary) 60%, white);
  --theme-secondary-dark: color-mix(in srgb, var(--theme-secondary) 80%, black);
  --theme-text-primary: var(--theme-text);
  --theme-text-secondary: rgba(var(--theme-text-rgb), 0.6);
  --theme-text-disabled: rgba(var(--theme-text-rgb), 0.38);
  --theme-placeholder: rgba(var(--theme-text-rgb), 0.48);
  --theme-background-default: var(--theme-background);
  --theme-divider: var(--theme-border);
  --theme-action-hover: rgba(var(--theme-text-rgb), 0.04);
  --theme-action-selected: rgba(var(--theme-text-rgb), 0.08);
  --theme-action-disabled: rgba(var(--theme-text-rgb), 0.26);
  --theme-action-disabled-background: rgba(var(--theme-text-rgb), 0.12);
  --theme-action-focus: rgba(var(--theme-text-rgb), 0.12);
  --theme-action-active: rgba(var(--theme-text-rgb), 0.54);
  --theme-success-light: color-mix(in srgb, var(--theme-success) 60%, white);
  --theme-success-dark: color-mix(in srgb, var(--theme-success) 80%, black);
  --theme-danger-light: color-mix(in srgb, var(--theme-danger) 60%, white);
  --theme-danger-dark: color-mix(in srgb, var(--theme-danger) 80%, black);
  --theme-warning-light: color-mix(in srgb, var(--theme-warning) 60%, white);
  --theme-warning-dark: color-mix(in srgb, var(--theme-warning) 80%, black);
  --theme-info-light: color-mix(in srgb, var(--theme-info) 60%, white);
  --theme-info-dark: color-mix(in srgb, var(--theme-info) 80%, black);
  --theme-teal-light: color-mix(in srgb, var(--theme-teal) 60%, white);
  --theme-teal-dark: color-mix(in srgb, var(--theme-teal) 80%, black);
  --theme-purple-light: color-mix(in srgb, var(--theme-purple) 60%, white);
  --theme-purple-dark: color-mix(in srgb, var(--theme-purple) 80%, black);
  --theme-neutral-light: color-mix(in srgb, var(--theme-neutral) 60%, white);
  --theme-neutral-dark: color-mix(in srgb, var(--theme-neutral) 80%, black);
  --theme-dark-light: color-mix(in srgb, var(--theme-dark) 60%, white);
  --theme-dark-dark: color-mix(in srgb, var(--theme-dark) 80%, black);
`

const sameColour = (a, b) => round8(parse(a)).join() === round8(parse(b)).join() && parse(a).a === parse(b).a

/**
 * One preset's legacy declarations for one mode.
 *  - old slot value-identical to the new token → omitted (the SCOPES alias covers it)
 *  - otherwise the verbatim old literal (secondary/accent always; material's rgba text)
 *  - `-rgb` triplets: verbatim in light; from the dark palette in dark
 *  - every other old `--theme-*` line the preset declared (tones, MUI action alphas, pillars)
 */
function legacyDecls(preset, palette, mode) {
  const legacy = preset.legacy ?? {}
  let out = ''
  if (mode === 'light') {
    for (const slot of LEGACY_SLOTS) {
      const old = legacy[`--theme-${slot}`]
      const alias = LEGACY_ALIAS[slot]
      if (old === undefined) {
        // No history (the `basecoat` preset): the two meaning-changed slots need a literal.
        if (slot === 'secondary') out += decl('--theme-secondary', oklch(palette.info))
        if (slot === 'accent') out += decl('--theme-accent', oklch(palette.ring))
        continue
      }
      if (alias && sameColour(old, palette[alias])) continue
      out += decl(`--theme-${slot}`, old)
    }
    for (const slot of RGB_SLOTS) {
      const key = `--theme-${slot}-rgb`
      out += decl(key, legacy[key] ?? rgbTriple(slot, palette, legacy))
    }
    for (const [name, value] of Object.entries(legacy)) {
      if (LEGACY_SLOTS.includes(name.replace('--theme-', ''))) continue
      if (name.endsWith('-rgb')) continue
      out += decl(name, value)
    }
  } else {
    for (const slot of RGB_SLOTS) out += decl(`--theme-${slot}-rgb`, rgbTriple(slot, palette, {}))
  }
  return out
}

function rgbTriple(slot, palette, legacy) {
  const alias = LEGACY_ALIAS[slot]
  const source = alias ? palette[alias]
    : slot === 'secondary' ? (legacy['--theme-secondary'] ?? palette.info)
    : (legacy['--theme-accent'] ?? palette.ring)
  return round8(parse(source)).join(', ')
}

/* ──────────────────────────────── build ───────────────────────────────── */

export function build() {
  const presets = JSON.parse(fs.readFileSync(PRESETS, 'utf8'))
  const vendor = readVendorBase()
  const names = Object.keys(presets).filter((k) => !k.startsWith('$'))

  // Resolve every preset to a complete light + dark palette.
  const resolved = {}
  for (const name of names) {
    const p = presets[name]
    if (p.vendor) {
      const fromVendor = (block) => {
        const o = {}
        for (const k of [...SEMANTIC, ...SIDEBAR]) {
          const v = block[cssName(k)]
          if (v && !v.startsWith('url(')) o[k] = v
        }
        return o
      }
      const light = completeLight({ ...fromVendor(vendor[':root']), ...p.light })
      const dark = completeDark(light, { ...fromVendor(vendor['.dark']), ...p.dark })
      resolved[name] = { light, dark, vendor: true }
    } else {
      const light = completeLight(p.light)
      // `dark: false` = the preset has NO dark mode: under html.dark it keeps its
      // light palette AND its light mode tokens (emitted in its dark block, which
      // out-specifies the :where() scopes rules).
      resolved[name] = p.dark === false
        ? { light, dark: light, noDark: true }
        : { light, dark: completeDark(light, p.dark ?? {}), derivedDark: !p.dark }
    }
  }

  const def = resolved[DEFAULT_PRESET]
  const nonColour = Object.entries(vendor[':root']).filter(([k]) =>
    !SEMANTIC.some((s) => cssName(s) === k) && !SIDEBAR.some((s) => cssName(s) === k) && k !== '--radius')
  const nonColourDark = Object.entries(vendor['.dark']).filter(([k]) =>
    !SEMANTIC.some((s) => cssName(s) === k) && !SIDEBAR.some((s) => cssName(s) === k))

  /* tokens.css */
  let rootBody = decl('color-scheme', 'light') + decl('--radius', vendor[':root']['--radius'])
  rootBody += `  /* Basecoat semantic tokens — the default palette (${DEFAULT_PRESET}) */\n`
  rootBody += paletteDecls(def.light, SEMANTIC)
  rootBody += `  /* Basecoat non-colour tokens (verbatim from vendor base.css) */\n`
  for (const [k, v] of nonColour) if (!hasVar(v)) rootBody += decl(k, v)
  // Font families read through the override hooks set ONLY by @mono-lit/helper/ui/font/*.css
  // (--mono-font-sans / --mono-font-mono on :root): unset → the theme's own family.
  rootBody += decl('--font-sans', `var(--mono-font-sans, ${vendor['@theme']['--font-sans']})`)
  rootBody += decl('--font-mono', `var(--mono-font-mono, ${vendor['@theme']['--font-mono']})`)
  rootBody += `  /* Tailwind engine subset the ported rules read */\n`
  for (const [k, v] of ENGINE) rootBody += decl(k, v)
  rootBody += `  /* mono control / type scale */\n`
  for (const [k, v] of SCALE) rootBody += decl(k, v)
  rootBody += `  /* mode tokens (light) */\n`
  for (const [k, l] of MODE) if (!hasVar(l)) rootBody += decl(k, l)

  // The default preset's dark block. A preset with no dark mode (ONE) keeps its
  // light palette and light mode tokens here, so html.dark is a no-op until a
  // preset that has one (theme-color-basecoat) is applied.
  let darkBody = decl('color-scheme', def.noDark ? 'light' : 'dark')
  darkBody += paletteDecls(def.dark, SEMANTIC)
  for (const [k, v] of def.noDark ? nonColour : nonColourDark) if (!hasVar(v)) darkBody += decl(k, v)
  darkBody += `  /* mode tokens (${def.noDark ? 'light — no dark mode' : 'dark'}) */\n`
  for (const [k, l, d] of MODE) if (!hasVar(def.noDark ? l : d)) darkBody += decl(k, def.noDark ? l : d)

  let scopesBody = `  /* var()-bearing tokens re-derive on every element a preset or mode class can land on */\n`
  for (const [k, v] of nonColour) if (hasVar(v)) scopesBody += decl(k, v)
  for (const [k, v] of ENGINE_DERIVED) scopesBody += decl(k, v)
  for (const [k, v] of SIDEBAR_DERIVED) scopesBody += decl(k, v)
  for (const [k, l] of MODE) if (hasVar(l)) scopesBody += decl(k, l)

  let darkScopesBody = ''
  for (const [k, l, d] of MODE) if (hasVar(def.noDark ? l : d)) darkScopesBody += decl(k, def.noDark ? l : d)

  const tokens = HEADER('token layer') +
    '@layer mono-tokens {\n' +
    rule(':root', rootBody) + rule(DARK_ROOT, darkBody) +
    rule(SCOPES, scopesBody) + rule(DARK_SCOPES, darkScopesBody) +
    '}\n' +
    '@keyframes mono-pulse { 50% { opacity: 0.5; } }\n'

  /* presets.css */
  let presetsCss = HEADER('colour presets') + '@layer mono-tokens {\n'
  for (const name of names) {
    const r = resolved[name]
    const keys = r.vendor ? [...SEMANTIC, ...SIDEBAR] : SEMANTIC
    let light = decl('--radius', vendor[':root']['--radius']) + paletteDecls(r.light, keys)
    if (r.vendor) for (const [k, v] of nonColour) if (!hasVar(v)) light += decl(k, v)
    let dark = paletteDecls(r.dark, keys)
    if (r.vendor) for (const [k, v] of nonColourDark) if (!hasVar(v)) dark += decl(k, v)
    dark = decl('color-scheme', r.noDark ? 'light' : 'dark') + dark
    for (const [k, l, d] of MODE) dark += decl(k, r.noDark ? l : d)
    presetsCss += `/* ${presets[name].displayName}${r.derivedDark ? ' — dark values DERIVED (review in ui/color.md)' : ''}${r.noDark ? ' — NO dark mode: stays light under html.dark' : ''} */\n`
    presetsCss += rule(`.theme-color-${name}`, light)
    presetsCss += rule(`.theme-color-${name}:is(${DARK_ROOT}, ${DARK_ROOT} *)`, dark)
  }
  presetsCss += '}\n'

  /* legacy.css */
  let legacyScopes = ''
  for (const [slot, token] of Object.entries(LEGACY_ALIAS)) legacyScopes += decl(`--theme-${slot}`, `var(--${token})`)
  for (const slot of CONTRAST_SLOTS) legacyScopes += decl(`--theme-${slot}-contrast`, `var(--${slot === 'danger' ? 'destructive' : slot}-foreground)`)
  legacyScopes += `  --theme-secondary-contrast: #ffffff;\n`
  for (const slot of MONO_RGB) legacyScopes += decl(`--mono-${slot}-rgb`, `var(--theme-${slot}-rgb)`)
  legacyScopes += LEGACY_ROOT_DERIVED.replace(/^\n/, '')

  let legacyCss = HEADER('pre-Basecoat --theme-* vocabulary, alive until 3.0') + '@layer mono-tokens {\n'
  // A preset's verbatim legacy line can itself contain var() (ONE's
  // --theme-action-selected); on :root that would go stale under a class, so
  // those lines join the scopes rule instead (after the default formulas, so
  // the preset's own wins).
  const rootLegacy = legacyDecls(presets[DEFAULT_PRESET], def.light, 'light').split('\n').filter(Boolean)
  legacyScopes += rootLegacy.filter((l) => hasVar(l)).map((l) => l + '\n').join('')
  legacyCss += rule(':root', rootLegacy.filter((l) => !hasVar(l)).map((l) => l + '\n').join('') + LEGACY_ROOT_LITERALS.replace(/^\n/, ''))
  legacyCss += rule(DARK_ROOT, legacyDecls(presets[DEFAULT_PRESET], def.dark, 'dark'))
  legacyCss += rule(SCOPES, legacyScopes)
  for (const name of names) {
    legacyCss += rule(`.theme-color-${name}`, legacyDecls(presets[name], resolved[name].light, 'light'))
    legacyCss += rule(`.theme-color-${name}:is(${DARK_ROOT}, ${DARK_ROOT} *)`, legacyDecls(presets[name], resolved[name].dark, 'dark'))
  }
  legacyCss += '}\n'

  return {
    files: { 'tokens.css': tokens, 'presets.css': presetsCss, 'legacy.css': legacyCss },
    resolved,
    names,
  }
}

export function check() {
  const { files } = build()
  const stale = []
  for (const [name, text] of Object.entries(files)) {
    const file = path.join(OUT_DIR, name)
    const have = fs.existsSync(file) ? fs.readFileSync(file, 'utf8').replace(/\r\n?/g, '\n') : ''
    if (have !== text) stale.push(name)
  }
  return stale
}

const isMain = process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)
if (isMain) {
  if (process.argv.includes('--check')) {
    const stale = check()
    if (stale.length) {
      console.error(`generated theme files are stale: ${stale.join(', ')} — run \`pnpm theme:build\``)
      process.exit(1)
    }
    console.log('generated theme files are current')
  } else {
    const { files, names } = build()
    fs.mkdirSync(OUT_DIR, { recursive: true })
    for (const [name, text] of Object.entries(files)) fs.writeFileSync(path.join(OUT_DIR, name), text)
    console.log(`wrote ${Object.keys(files).join(', ')} for ${names.length} presets (default: ${DEFAULT_PRESET}) → ${path.relative(root, OUT_DIR)}`)
    const docs = path.join(root, 'scripts', 'theme-docs.mjs')
    if (fs.existsSync(docs)) {
      const { execFileSync } = await import('node:child_process')
      execFileSync(process.execPath, [docs], { stdio: 'inherit' })
    }
  }
}
